# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SimpanAtribut
                                 A QGIS plugin
 Menyimpan atribut dari layer yang dipilih kedalam file text
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-30
        copyright            : (C) 2024 by Wawan Hendriawan Nur
        email                : wawanhn@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SimpanAtribut class from file SimpanAtribut.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .simpan_atribut import SimpanAtribut
    return SimpanAtribut(iface)
